window.GLACIERCODE_STORAGE_KEY = "glaciercode_catalog_v1";
window.GLACIERCODE_SETTINGS_KEY = "glaciercode_site_settings_v1";

window.GLACIERCODE_DEFAULT_SETTINGS = {
  brandName: "GlacierStore",
  whatsappNumber: "6281234567890",
  telegramUsername: "iptstore_id",
  adminHours: {
    open: "08:00",
    close: "22:00",
    autoOffline: true,
    showCountdown: true,
    disclaimer: "Jam Operasional bisa berubah sewaktu waktu",
    lastOrderEnabled: true,
    lastOrderMinutes: 15,
    lastOrderMessage: "Last Order: Selesaikan pesananmu sekarang!",
  },
  systemMaintenance: {
    enabled: false,
    start: "",
    end: "",
    message: "Website sedang dalam pemeliharaan sistem. Silakan kembali setelah pemeliharaan selesai.",
    contactUrgent: true,
  },
  infoBanner: {
    enabled: true,
    message: "Informasi: Pemeliharaan rutin setiap hari pukul {maintenance_start} - {maintenance_end}. Jam operasional transaksi: {open} - {close}.",
  },
};

window.GLACIERCODE_DEFAULT_GAMES = [
  {
    id: "free-fire",
    name: "Free Fire",
    initials: "FF",
    imageUrl: "",
    featured: false,
    from: "Mulai Rp9.800",
    colors: ["#2f9c8f", "#d9784b"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "70 Diamond", price: "Rp9.800", status: "normal", statusLabel: "" },
      { name: "140 Diamond", price: "Rp18.900", normal: "Rp20.000", promo: true, status: "normal", statusLabel: "", costPrice: "16449" },
      { name: "200 Diamond", price: "Rp18.700", status: "normal", statusLabel: "" },
      { name: "355 Diamond", price: "Rp45.500", status: "normal", statusLabel: "" },
      { name: "720 Diamond", price: "Rp91.000", normal: "Rp96.000", promo: true, status: "normal", statusLabel: "" },
      { name: "Membership Mingguan", price: "Rp29.500", status: "normal", statusLabel: "" },
      { name: "Membership Bulanan", price: "Rp88.000", status: "normal", statusLabel: "" },
      { name: "Booyah Pass", price: "Rp15.000", status: "normal", statusLabel: "" },
      { name: "BP Card", price: "Rp43.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "mobile-legends",
    name: "Mobile Legends",
    initials: "ML",
    imageUrl: "",
    from: "Mulai Rp12.500",
    colors: ["#4658a8", "#2f9c8f"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "44 Diamond", price: "Rp12.500", status: "normal", statusLabel: "" },
      { name: "86 Diamond", price: "Rp21.500", normal: "Rp23.000", promo: true, status: "normal", statusLabel: "" },
      { name: "172 Diamond", price: "Rp42.000", status: "normal", statusLabel: "" },
      { name: "257 Diamond", price: "Rp62.000", status: "normal", statusLabel: "" },
      { name: "344 Diamond", price: "Rp82.000", status: "normal", statusLabel: "" },
      { name: "429 Diamond", price: "Rp101.000", status: "normal", statusLabel: "" },
      { name: "Weekly Diamond Pass", price: "Rp28.000", status: "normal", statusLabel: "" },
      { name: "Starlight Member", price: "Rp155.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "pubg-mobile",
    name: "PUBG Mobile",
    initials: "PM",
    imageUrl: "",
    from: "Mulai Rp14.500",
    colors: ["#3e4b5f", "#e9b44c"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "60 UC", price: "Rp14.500", status: "normal", statusLabel: "" },
      { name: "325 UC", price: "Rp69.000", normal: "Rp73.000", promo: true, status: "normal", statusLabel: "" },
      { name: "660 UC", price: "Rp137.000", status: "normal", statusLabel: "" },
      { name: "1800 UC", price: "Rp345.000", status: "normal", statusLabel: "" },
      { name: "3850 UC", price: "Rp690.000", status: "normal", statusLabel: "" },
      { name: "8100 UC", price: "Rp1.375.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "valorant",
    name: "Valorant",
    initials: "VA",
    imageUrl: "",
    from: "Mulai Rp15.000",
    colors: ["#bf4f51", "#10131c"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "125 Points", price: "Rp15.000", status: "normal", statusLabel: "" },
      { name: "420 Points", price: "Rp50.000", status: "normal", statusLabel: "" },
      { name: "700 Points", price: "Rp80.000", status: "normal", statusLabel: "" },
      { name: "1375 Points", price: "Rp150.000", normal: "Rp160.000", promo: true, status: "normal", statusLabel: "" },
      { name: "2400 Points", price: "Rp250.000", status: "normal", statusLabel: "" },
      { name: "4000 Points", price: "Rp400.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "genshin",
    name: "Genshin Impact",
    initials: "GI",
    imageUrl: "",
    from: "Mulai Rp14.000",
    colors: ["#5e7a9d", "#d9784b"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "60 Genesis Crystal", price: "Rp14.000", status: "normal", statusLabel: "" },
      { name: "300 + 30 Crystal", price: "Rp69.000", status: "normal", statusLabel: "" },
      { name: "980 + 110 Crystal", price: "Rp219.000", status: "normal", statusLabel: "" },
      { name: "Blessing Welkin Moon", price: "Rp68.000", normal: "Rp72.000", promo: true, status: "normal", statusLabel: "" },
      { name: "Battle Pass Gnostic Hymn", price: "Rp139.000", status: "normal", statusLabel: "" },
      { name: "1980 + 260 Crystal", price: "Rp429.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "honkai-star-rail",
    name: "Honkai Star Rail",
    initials: "HS",
    imageUrl: "",
    from: "Mulai Rp14.000",
    colors: ["#5661a6", "#b56fba"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "60 Oneiric Shard", price: "Rp14.000", status: "normal", statusLabel: "" },
      { name: "300 + 30 Shard", price: "Rp69.000", status: "normal", statusLabel: "" },
      { name: "980 + 110 Shard", price: "Rp219.000", status: "normal", statusLabel: "" },
      { name: "Express Supply Pass", price: "Rp68.000", normal: "Rp72.000", promo: true, status: "normal", statusLabel: "" },
      { name: "Nameless Glory", price: "Rp139.000", status: "normal", statusLabel: "" },
      { name: "1980 + 260 Shard", price: "Rp429.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "roblox",
    name: "Roblox",
    initials: "RB",
    imageUrl: "",
    from: "Mulai Rp16.000",
    colors: ["#4f5967", "#9aa5b1"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "80 Robux", price: "Rp16.000", status: "normal", statusLabel: "" },
      { name: "400 Robux", price: "Rp78.000", status: "normal", statusLabel: "" },
      { name: "800 Robux", price: "Rp154.000", normal: "Rp160.000", promo: true, status: "normal", statusLabel: "" },
      { name: "1700 Robux", price: "Rp310.000", status: "normal", statusLabel: "" },
      { name: "Premium 450", price: "Rp82.000", status: "normal", statusLabel: "" },
      { name: "Premium 1000", price: "Rp165.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "codm",
    name: "Call of Duty M",
    initials: "CM",
    imageUrl: "",
    from: "Mulai Rp5.000",
    colors: ["#2d3d32", "#d9a03f"],
    status: "normal",
    statusLabel: "",
    products: [
      { name: "31 CP", price: "Rp5.000", status: "normal", statusLabel: "" },
      { name: "63 CP", price: "Rp10.000", status: "normal", statusLabel: "" },
      { name: "128 CP", price: "Rp20.000", status: "normal", statusLabel: "" },
      { name: "321 CP", price: "Rp49.000", normal: "Rp53.000", promo: true, status: "normal", statusLabel: "" },
      { name: "645 CP", price: "Rp98.000", status: "normal", statusLabel: "" },
      { name: "1373 CP", price: "Rp196.000", status: "normal", statusLabel: "" },
    ],
  },
  {
    id: "arena-breakout",
    name: "Arena Breakout",
    initials: "AB",
    imageUrl: "",
    from: "Cek admin",
    colors: ["#303742", "#2f9c8f"],
    status: "normal",
    statusLabel: "",
    products: [],
  },
];
